### ISSUE TITLE
Créer ou Modifier un employé

### ISSUE THREAD

**Issue by jodelin93** [jodelin93/New-Vision-LebensSoft#1]
Entant que Administrateur ou Responsable de ressources humaines, je veux Enregistrer un nouveau employé dans LBS, afin de lui donner accès à ses fonctionnalités. 

Pré-conditions: L'Administrateur est authentifié dans LBS avec les droits d'administrateur. L'administrateur a cliqué sur l'onglet "Administration" puis sur l'option "Employés" et il navigue dans la liste des employés.
Déclencheur: :'administrateur a cliqué sur un employé existant (pour modifier) ou a cliqué "Ajouter" (pour créer un nouvel employé).
Déroulement:
1. LBS affiche la page "Créer ou modifier un employé", avec les champs suivants:
   - Code employer: Généré par LBS comme suit:
      - Les 3 premiers caractères du nom de famille concaténé avec "-" plus un numéro séquentiel correspondant un nombre d'employés inscrits.
   - Nom: 50 caractères
   - Prénom(s): 50 caractères
   - Statut: liste déroulante ou radio-boutons ou autres "En Service" ou "Suspendu"
   - Adresse de l'employer
   - Poste de l'employer
   - E-mail de l'employer
   - Son numero de telephone
   - le numero de sa carte d'identification nationale (CIN)
1. En mode création, tous les champs sont vides. En mode modification, LBS affiche les informations de l'employés provenant de la base de données.
1. L'Administrateur entre ou modifie les champs.
1. L'Administrateur clique sur "Valider".
1. LBS vérifie les données --> en cas d'erreur, afficher le message d'erreur approprié.
1. LBS modifie les informations de l'employé dans la base de données.

**Comment by inno1OO** [comment]
Liste des cas de test :
1.-L'utilisateur saisit de bonnes informations
LBS affiche un message notifiant ke l'enregistrement est reussi
2.-L'utilisateur saisit une chaine de caracters dans un champ de type number
LBS empechea saisie
3.- L'utilisateur a oublie de mettre une ou des informations importantes
LBS affiche un mesage d'erreur notifiant le ou les champs qui sont vides.

**Comment by inno1OO** [comment]
Liste des cas de test:
1.- L'utilisateur n'a pas saisi une information obligatoire
LBS affiche une erreur tout en precisant le ou les champs qui n'ont pas ete rempli
2.-  L'utilisateur a saisi un mauvais type de donee
LBS affiche un message d'erreur approprie
