### ISSUE TITLE
Lister et rechercher les Parrainés

### ISSUE THREAD

**Issue by jodelin93** [jodelin93/New-Vision-LebensSoft#19]
En tant que Administrateur, je veux faire la gestion des parrainés.

Pré-condition: Etre connecter sur Lebens-Soft
Déclencheur: Clique sur l'onglet parrainage, puis sur l'onglet liste des parrains
Déroulement: Lebens-Soft affiche la liste des parrains, dans cette liste on peut modifier un parrain mais aussi d'ajouter un.

**Comment by strudelauxpommes** [comment]
Liste de cas de test:
1. 
1.
1.
