### ISSUE TITLE
S'authentifier sur le Systeme

### ISSUE THREAD

**Issue by jodelin93** [jodelin93/New-Vision-LebensSoft#7]
Entant qu’utilisateur de Lebens Soft (LBS), je veux m'authentifier afin d'avoir acces aux differents fonctionnalites de LBS en fonction de mes droits d'acces.
Déclencheur: L'utilisateur a accédé à Lebens Soft.
Déroulement:
1. L'utilisateur entre son nom d'utilisateur et son mot de passe. Il appuie sur "Se Connecter".
1. LBS vérifie que :
   - le nom d'utilisateur existe et est actif
   - le mot de passe est identique au mot de passe enregistré de cet utilisateur.
1. Quand l'authentification se fait avec succès:
   - LBS lit les accès de cet utilisateur.
   - L'utilisateur a accès au tableau de bord de l’application qui va lui permettre d'effectuer différentes opérations selon l’accès qu'il a sur le système.
1. Quand il y a ÉCHEC d'authentification, LBS affiche le message "Nom utilisateur ou mot de passe invalide ou inactif".

Au cas où l’utilisateur oublie son mot de passe ou son nom d’utilisateur, il doit  avertir l’administrateur du système pour réinitialiser son compte. Par la suite, il pourra réinitialiser son mot de passe utilisateur.

**Comment by strudelauxpommes** [comment]
Liste des cas de test:
1. Utilisateur normal, actif, avec un bon mot de passe.
1. Compte utilisateur qui n'existe pas --> Message d'erreur
1. Compte utilisateur inactif --> Message d'erreur
1. Mot de passe erroné --> Message d'erreur
1. S'authentifier après que l'administrateur ait ré-initialisé le compte.
